version: '3.8'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: healthcare_redis
    ports:
      - "6379:6379"  # The Port for code to talk to Redis
      - "8001:8001"  # The UI Dashboard (optional but cool)
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: